export const CONTACT = {
  phone: "+91 7075851158",
  phoneLink: "tel:+917075851158",
  email: "info@amaramam.com",
  emailLink: "mailto:info@amaramam.com",
  address: "Vijayawada, Andhra Pradesh, India",
  whatsapp: "https://wa.me/917075851158",
};

export const SOCIAL_LINKS = {
  linkedin: "https://www.linkedin.com/company/110902850/admin/dashboard/",
  instagram: "https://www.instagram.com/amaramamskillhub/",
  facebook: "https://www.facebook.com/profile.php?id=61585622655175",
  twitter: "https://x.com/amaramamskill",
  whatsapp: "https://whatsapp.com/channel/0029VbC45GCFsn0aw7jqEI3M",
  telegram: "https://t.me/+n-xBu9yk-7s3YWE1",
  youtube: "https://www.youtube.com/@amaramamskillhub",
  google: "https://share.google/fzNNiFg5A44HoQAwL",
};

export const COURSES = [
  {
    title: "Quantum Technology",
    description: "Explore the fundamentals of quantum computing, quantum algorithms, and their real-world applications.",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=250&fit=crop",
    category: "Emerging Tech",
    rating: 4.7,
    duration: "8 weeks",
    students: "800",
    price: 4000,
  },
  {
    title: "Artificial Intelligence (AI)",
    description: "Master AI concepts including neural networks, NLP, and computer vision with hands-on projects.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop",
    category: "AI/ML",
    rating: 4.9,
    duration: "8 weeks",
    students: "3,200",
    price: 4000,
  },
  {
    title: "Machine Learning (ML)",
    description: "Build predictive models using supervised and unsupervised learning techniques with Python.",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop",
    category: "AI/ML",
    rating: 4.8,
    duration: "8 weeks",
    students: "2,800",
    price: 4000,
  },
  {
    title: "Data Science",
    description: "Analyze data, build models, and create dashboards using Python, Pandas, and visualization tools.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    category: "AI/ML",
    rating: 4.8,
    duration: "8 weeks",
    students: "2,700",
    price: 4000,
  },
  {
    title: "Cybersecurity",
    description: "Learn ethical hacking, network security, and threat analysis to protect digital infrastructure.",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop",
    category: "IT & Security",
    rating: 4.7,
    duration: "8 weeks",
    students: "1,900",
    price: 4000,
  },
  {
    title: "Blockchain Development",
    description: "Build decentralized apps and smart contracts using Ethereum, Solidity, and Web3 technologies.",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=250&fit=crop",
    category: "Emerging Tech",
    rating: 4.6,
    duration: "8 weeks",
    students: "1,500",
    price: 4000,
  },
  {
    title: "UI/UX Design",
    description: "Design user-centered interfaces using Figma, prototyping, and design thinking principles.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    category: "Design",
    rating: 4.8,
    duration: "8 weeks",
    students: "2,400",
    price: 4000,
  },
  {
    title: "Full Stack Web Development",
    description: "Master front-end and back-end technologies including React, Node.js, and databases.",
    image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=250&fit=crop",
    category: "Development",
    rating: 4.9,
    duration: "12 weeks",
    students: "3,500",
    price: 4000,
  },
  {
    title: "Digital Marketing",
    description: "Learn SEO, social media marketing, Google Ads, content marketing, and analytics.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
    category: "Marketing",
    rating: 4.7,
    duration: "8 weeks",
    students: "2,600",
    price: 4000,
  },
  {
    title: "Robotics & Automation",
    description: "Build and program robots using sensors, actuators, and automation frameworks.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=250&fit=crop",
    category: "Emerging Tech",
    rating: 4.6,
    duration: "10 weeks",
    students: "1,200",
    price: 4000,
  },
  {
    title: "Internet of Things (IoT)",
    description: "Connect devices, sensors, and systems to build smart IoT solutions and dashboards.",
    image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=400&h=250&fit=crop",
    category: "Emerging Tech",
    rating: 4.5,
    duration: "8 weeks",
    students: "1,100",
    price: 4000,
  },
  {
    title: "AR/VR Development",
    description: "Create immersive augmented and virtual reality experiences using Unity and modern XR tools.",
    image: "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=400&h=250&fit=crop",
    category: "Emerging Tech",
    rating: 4.6,
    duration: "10 weeks",
    students: "900",
    price: 4000,
  },
  {
    title: "DevOps Fundamentals",
    description: "Master CI/CD pipelines, Docker, Kubernetes, and cloud deployment strategies.",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=250&fit=crop",
    category: "IT & Security",
    rating: 4.7,
    duration: "8 weeks",
    students: "2,000",
    price: 4000,
  },
  {
    title: "Mobile App Development",
    description: "Build cross-platform mobile apps using React Native and Flutter with real projects.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    category: "Development",
    rating: 4.8,
    duration: "10 weeks",
    students: "2,300",
    price: 4000,
  },
  {
    title: "Cloud Computing",
    description: "Master AWS, Azure, and GCP fundamentals including deployment, scaling, and cloud architecture.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&h=250&fit=crop",
    category: "IT & Security",
    rating: 4.6,
    duration: "8 weeks",
    students: "2,100",
    price: 4000,
  },
];

export const TESTIMONIALS = [
  {
    quote: "Amaramam Skill Hub transformed my career. The full-stack course gave me the confidence to land my dream job!",
    name: "Arun Kumar",
    role: "Web Developer at TCS",
    course: "Full Stack Web Development",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
  },
  {
    quote: "The AI/ML course was incredibly well-structured. The hands-on projects made all the difference.",
    name: "Meena Reddy",
    role: "ML Engineer at Infosys",
    course: "Artificial Intelligence",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
  },
  {
    quote: "Best investment I made in myself. The mentors are incredibly supportive and knowledgeable.",
    name: "Sanjay Das",
    role: "UX Designer at Wipro",
    course: "UI/UX Design",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
  },
  {
    quote: "Went from zero to running campaigns for multiple clients. Amaramam's practical approach is unmatched.",
    name: "Priya Nair",
    role: "Digital Marketing Lead",
    course: "Digital Marketing",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop",
  },
  {
    quote: "The cybersecurity course opened up a whole new career path for me. Highly recommended!",
    name: "Karthik R",
    role: "Security Analyst at HCL",
    course: "Cybersecurity",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop",
  },
  {
    quote: "I learned cloud computing from scratch and got certified within 3 months. Amazing experience!",
    name: "Deepika Shetty",
    role: "Cloud Engineer",
    course: "Cloud Computing",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
  },
];
